# arm:
#  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
# arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   solve_type: Distance
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_attempts: 5
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
# arm_with_torso:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_attempts: 3
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
